### ISSUE TITLE
Flickering lights

### ISSUE THREAD

**Issue by Talon1024** [coelckers/gzdoom#1404] opened 2021-06-01 15:20 UTC
Dynamic lights seem to be flickering, as can be seen with Dusted's Pandemonia 2.1.2 on Plutonia 2 MAP29 "Ticket to Eternity" here:

https://user-images.githubusercontent.com/6550500/120348555-4a8f7f80-c2cb-11eb-831f-42e2b3283fce.mp4

Here's the WAD load order:

    PL2.WAD
    freetonia.wad (Freedoom Plutonia texture pack)
    plut2_zdoom.pk3 (Xeotroid's Plutonia 2 music pack)
    Pandemonia-v2.1.2.pk3

If need be, I can provide a saved game.

**Comment by vsonnier** [comment] 2021-06-01 17:04
This is likely a duplicate of https://forum.zdoom.org/viewtopic.php?f=7&t=72432 or https://forum.zdoom.org/viewtopic.php?f=7&t=72443, which has been fixed already on `master`.

**Comment by Gaerzi** [comment] 2021-06-01 19:52
Most likely a duplicate, yes.

**Closed by Gaerzi** 2021-06-01 19:52 UTC
