### ISSUE TITLE
[BUG] Skybox on Vulkan Render is Visually Glitched

### ISSUE THREAD

**Issue by kinker31** [coelckers/gzdoom#1593] opened 2022-04-23 23:34 UTC
### GZDoom version

Git Version

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Fedora Linux 35 (MATE-Compiz), Linux 5.15.10-200.fc35.x86_64 on x86_64

### Relevant hardware info

AMD Ryzen 3 3100 4-Core Processor (CPU), Radeon RX 6600/6600 XT/6600M (GPU)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

(This bug shows up on any IWAD I try running, I picked Doom 2 'cause that's what I mostly play)

On the Vulkan renderer, regardless if HDR's turned on or not, whenever I head over to an area that has F_SKY1 for a ceiling, half of the sky's able to render correctly, but the other half's either pitch-black, a light green, or a solid magenta. Everything else renders fine (at least if nothing else's loaded that requires any special rendering, as far as I know of), but it's _just_ the sky that's wonky

![Screenshot_Doom_20220423_181234](https://user-images.githubusercontent.com/16625998/164949383-a3e5c066-76bc-4c85-9293-b48f5af542a7.png)
![Screenshot_Strife_20220423_182349](https://user-images.githubusercontent.com/16625998/164949385-f6736fbe-559e-4aa4-9b69-9944ec7d5817.png)
.

### Steps to reproduce the behaviour.

1. Clone, build, and install the latest build of GZDoom
2. Run the game, and select any IWAD
3. Start the game, and head over to the closest skybox you can see.

### Your configuration

```ini
The config's in an attachment over at the "Provide a Log" section of the report.
```

### Provide a Log

[log.txt](https://github.com/coelckers/gzdoom/files/8548779/log.txt)

[gzdoom.ini.tar.gz](https://github.com/coelckers/gzdoom/files/8548776/gzdoom.ini.tar.gz)

**Comment by coelckers** [comment] 2022-04-24 05:44
Duplicate of https://forum.zdoom.org/viewtopic.php?f=290&t=74834

**Closed by coelckers** 2022-04-24 05:44 UTC
Labels: bug
